services: 
  html-app: 
    image: hehe/frontend
    build: 
      context: web_app
      dockerfile: ./Dockerfile
    depends_on:
      - hehe-api
    volumes:
      - ./web_app/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - "8080:80"

  hehe-api:
    image: hehe/backend
    build: ./deno_api
    ports:
      - "4200:80"
