
[[language]]
language-servers = ["gleam", "tailwind"]
name = "gleam"

[language-server.tailwind.config.tailwindCSS.experimental]
classRegex = ["class\\(.*?\\)(?!\\])", "(?:'|\"|`)([^\"'`]*)(?:'|\"|`)"]
